### PR TITLE
Replaced Javascript with logo

### PR DESCRIPTION
**Pull request by CaptainYarb**
This addresses Issue #6 and uses the logo from https://github.com/voodootikigod/logo.js

### CODE REVIEW

**Comment by fuzzyalej** [comment]
Hi @blazedd,
thanks for the contribution! Would you mind creating a new js poster instead of overwriting the old one? 

We really like the minimalistic approach and would not like to lose the 'original' js poster!

Thanks again

**Comment by derhuerst** [comment]
ping @blazedd (:

**Comment by CaptainYarb** [comment]
Sorry about the delay. I had this on my work computer and hadn't been at the office in a few days. There ya go. :+1:

**Comment by fuzzyalej** [comment]
Thanks @blazedd,
would you mind undo the renaming of the `.ai` file so it stays as it is right now?

Thanks :+1:

**Pull request merged**
